# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestRun1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(470, 432)
        Form.setMinimumSize(QtCore.QSize(470, 432))
        Form.setMaximumSize(QtCore.QSize(470, 432))
        Form.setStyleSheet("background-color: rgb(22, 163, 228);")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 300, 471, 20))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"selection-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(0, 0, 0);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(35)
        self.line.setMidLineWidth(35)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.AltitudeOutput = QtWidgets.QLabel(Form)
        self.AltitudeOutput.setGeometry(QtCore.QRect(-10, 380, 151, 16))
        self.AltitudeOutput.setStyleSheet("\n"
"\n"
"font: 15pt \"OCR A Extended\";")
        self.AltitudeOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.AltitudeOutput.setObjectName("AltitudeOutput")
        self.Timeoutput = QtWidgets.QLabel(Form)
        self.Timeoutput.setGeometry(QtCore.QRect(350, 380, 121, 20))
        self.Timeoutput.setStyleSheet("font: 15pt \"Roboto\";")
        self.Timeoutput.setAlignment(QtCore.Qt.AlignCenter)
        self.Timeoutput.setObjectName("Timeoutput")
        self.altitudeTitle = QtWidgets.QLabel(Form)
        self.altitudeTitle.setGeometry(QtCore.QRect(20, 350, 91, 20))
        self.altitudeTitle.setStyleSheet("\n"
"\n"
"font: 15pt \"OCR A Extended\";")
        self.altitudeTitle.setObjectName("altitudeTitle")
        self.lblTime = QtWidgets.QLabel(Form)
        self.lblTime.setGeometry(QtCore.QRect(390, 350, 51, 20))
        self.lblTime.setStyleSheet("\n"
"\n"
"font: 15pt \"OCR A Extended\";")
        self.lblTime.setObjectName("lblTime")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.AltitudeOutput.setText(_translate("Form", "320459205m"))
        self.Timeoutput.setText(_translate("Form", "4s"))
        self.altitudeTitle.setText(_translate("Form", "Altitude"))
        self.lblTime.setText(_translate("Form", "Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
